apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api-deployment
spec:
  selector:
    matchLabels:
      app: go-api
  replicas: 2 
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
      - name: go-rest-api
        image: akashsawan/rest-api
        ports:
        - containerPort: 8080
